apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secureflow-ingress-local
  namespace: secureflow
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: secureflow
            port:
              number: 80
