apiVersion: v1
kind: Secret
metadata:
  name: secureflow-secret
  namespace: secureflow
type: Opaque
data:
  # Base64 for "secureflow"
  SPRING_DATASOURCE_USERNAME: c2VjdXJlZmxvdw==
  # Base64 for "secureflow"
  SPRING_DATASOURCE_PASSWORD: c2VjdXJlZmxvdw==

# Comment: Use Kubernetes Secrets, SealedSecrets or AWS Secrets Manager / Vault in production setups.
# This file is committed with base64 dummy values for local Kind cluster bootstrap.
