global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080', 'secureflow.secureflow.svc.cluster.local:80']
        labels:
          application: 'secureflow-api'

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    # Note: Falls back gracefully if running in a simple non-K8s docker compose environment
